### ISSUE TITLE
How to call a method?

### ISSUE THREAD

**Issue by doimet** [cloud-custodian/cel-python#34]
```python
import celpy


class RewriteString(str):
    def __new__(cls, value):
        return super().__new__(cls, value)

    def contains(self, value):
        if value in self:
            return True
        else:
            return False


cel_source = "account.username == admin && account.password.contains('FI')"

env = celpy.Environment()
ast = env.compile(cel_source)
prgm = env.program(ast)

activation = {
    "account": celpy.json_to_cel(
        {
            "username": "admin",
            "password": {
                "contains": RewriteString('4wtFI8W7').contains
            }
        }
    ),
}
result = prgm.evaluate(activation)
print(result)
```
Exception:
```python
Traceback (most recent call last):
  File "D:\test.py", line 22, in <module>
    "account": celpy.json_to_cel(
  File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\celpy\adapter.py", line 130, in json_to_cel
    {json_to_cel(key): json_to_cel(value) for key, value in document.items()}
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\celpy\adapter.py", line 130, in <dictcomp>
    {json_to_cel(key): json_to_cel(value) for key, value in document.items()}
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\celpy\adapter.py", line 130, in json_to_cel
    {json_to_cel(key): json_to_cel(value) for key, value in document.items()}
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\celpy\adapter.py", line 130, in <dictcomp>
    {json_to_cel(key): json_to_cel(value) for key, value in document.items()}
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\celpy\adapter.py", line 137, in json_to_cel
    raise ValueError(f"unexpected type {type(document)} in JSON structure {document!r}")
ValueError: unexpected type <class 'method'> in JSON structure <bound method RewriteString.contains of '4wtFI8W7'>
```

**Comment by slott56** [comment]
It's not clear what this is supposed to do. I don't think there's a provision in the CEL specification for providing a method that will be executed at run time. 

What are you trying to do?
